### ISSUE TITLE
TypeError: ufunc 'isfinite' not supported for the input types

### ISSUE THREAD

**Issue by optio50** [domarm-comat/pglive#36]
I have several charts plotting data from several remote sources.
If the remote data generator reboots some of the remote resources come back online faster than others.
The source that generates the below error takes up to a minute  longer than the rest.
The other charts seem to restart charting without a noticeable effect.

I dont know how to handle this error.
A try except block in the chart update does not work as expected.

Any Ideas?

Traceback (most recent call last):
  File "/home/chromebox/.local/lib/python3.10/site-packages/pglive/sources/live_mixins.py", line 35, in slot_new_data
    self.setData(x, y, **kwargs)
  File "/home/chromebox/.local/lib/python3.10/site-packages/pyqtgraph/graphicsItems/PlotDataItem.py", line 819, in setData
    self.updateItems( styleUpdate = self.property('styleWasChanged') )
  File "/home/chromebox/.local/lib/python3.10/site-packages/pyqtgraph/graphicsItems/PlotDataItem.py", line 865, in updateItems
    dataset = self._getDisplayDataset()
  File "/home/chromebox/.local/lib/python3.10/site-packages/pyqtgraph/graphicsItems/PlotDataItem.py", line 1034, in _getDisplayDataset
    data_range = self._datasetMapped.dataRect()
  File "/home/chromebox/.local/lib/python3.10/site-packages/pyqtgraph/graphicsItems/PlotDataItem.py", line 84, in dataRect
    self._updateDataRect()
  File "/home/chromebox/.local/lib/python3.10/site-packages/pyqtgraph/graphicsItems/PlotDataItem.py", line 58, in _updateDataRect
    selection = np.isfinite(self.y)    # We are looking for the bounds of the plottable data set. Infinite and Nan are ignored. 
TypeError: ufunc 'isfinite' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

**Comment by optio50** [comment]
Seems to have been solved by explicitly declaring the data point as a float and the try except block also works.  ¯\_ (ツ)_/¯

**Comment by optio50** [comment]
Wii reopen if needed
